- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ssl_verify: "False"
  tasks:
  - name: Configure local users.
    fortios_user_local:
      vdom:  "{{ vdom }}"
      state: "present"
      user_local:
        auth_concurrent_override: "enable"
        auth_concurrent_value: "4"
        authtimeout: "5"
        email_to: "{{ user_email }}"
#        id:  "8"
        name: "{{ user_name }}"
        passwd: "{{ user_password }}"
        status: "enable"
        two_factor: "disable"
        type: "password"
