- hosts: fortivm7
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ssl_verify: "False"
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        system_global:
            hostname: 'FortiVM7'
