- hosts: fortivm7
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
    vdom: "root"
    ssl_verify: "False"
  tasks:
   - name: Configure Test Interface Port2 
     fortios_system_interface:
        vdom:  "{{ vdom }}"
        state: "present"
        system_interface:
          name: port2
          ip: "192.168.0.144/24"
          interface: "port2"
          alias: "TEST_INTERFACE"
          allowaccess: 
            - "https"
            - "ping"
            - "ssh"
