- hosts: all
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
    vdom: "root"
    ssl_verify: "False"
  tasks:
   - name: Configure Interface Fortigate
     fortios_system_interface:
        vdom:  "{{ vdom }}"
        state: "present"
        system_interface:
          name: "{{ port_number }}"
          ip: "{{ net_interface }}"
          interface: "{{ port_number }}"
          alias: "{{ alias_name }}"
          status: up
          allowaccess: "{{ allow_access }}"
