- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
   vdom: "root"
   ssl_verify: "False"
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        system_global:
            timezone: "{{ time_zone }}"
